# Generated by Django 4.0 on 2023-11-20 04:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='テスト名')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Japanese', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.RegexValidator(message='正しい得点を入力してください')], verbose_name='国語')),
                ('Math', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.RegexValidator(message='正しい得点を入力してください')], verbose_name='数数学')),
                ('Science', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.RegexValidator(message='正しい得点を入力してください')], verbose_name='理科')),
                ('Sociology', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.RegexValidator(message='正しい得点を入力してください')], verbose_name='社会')),
                ('English', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), django.core.validators.RegexValidator(message='正しい得点を入力してください')], verbose_name='英語')),
                ('testtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.testtitle', verbose_name='テスト名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='氏名')),
            ],
        ),
    ]
